name: auto merge

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# Trigger: On merge of Develop to Master
# todo: how to make it only from develop?
on:
  pull_request:
    branches: [ master ]

jobs:
    merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge to X branch
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: 'biz'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      

        
        
