# Ticket: FOUNDSRE-79
# Description: On update of MASTER merge MASTER to BRANCH
#
# Original request was on merge of DEVELOP to MASTER merge
#    MASTER to a list of branches.  Send Slack message on merge failure
#
# Requires SLACK_WEBHOOK_URL Slack app set up as Hithub secret
#
# Phase 1: On any merge to MASTER merge MASTER to one branch: sour
#
# TODO: Merge to multiple branches, parameterize
# TODO: Restrict on only merge of DEVELOP to MASTER
  

name: Auto merge MASTER branch to SOUR
#on: [push, pull_request, issues]  #for testing
on:
  pull_request:
    branches:
      - 'develop'
    types: [ closed ]

jobs:
  merge-branch:
    name: merge-branch
    
    # needed so the Slack message sends after is merge fails
    continue-on-error: true 
    runs-on: ubuntu-latest
    steps:
      #checkout MASTER
      - uses: actions/checkout@master
      
      #merge MASTER to SOUR
      - name: Merge to sour branch
        uses: devmasx/merge-branch@v1.1.0
        if: github.head_ref == 'refs/heads/master'
        with:
          type: now
          target_branch: 'sour'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      #if the merge fails, send a Slack message
      - uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
