name: Merge staging branch to vast
#on: [push, pull_request, issues]
on:
  push:
    branches:
      - 'master'

jobs:
  job-merge-branch:
    name: merge-branch
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge to vast branch
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: 'vast'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  
  
  
