name: Merge staging branch to vast
on: [push, pull_request, issues]
#on: [push: branches: master ]
#  push:
#    branches:
#      - 'master'

jobs:
  job-merge-branch:
    name: merge-branch x
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge to vast branch
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: 'vast'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
 
  
  
  job-slackNotification:
    name: Slack Notification x
    needs: job-merge-branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
