# This is a basic workflow to help you get started with Actions

name: auto merge

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# Trigger: On merge of Develop to Master
on:
  # todo: how to make it only from develop?
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # 
    merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge to uat branch
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: 'biz'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      
    #slackNotification:
    # name: Slack Notification
    # runs-on: ubuntu-latest
    # steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        #todo change message and only call on error
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        
        
