# Ticket: FOUNDSRE-79
# Description: On closed pull request from master to develop, merge master to a list of branches
  

name: Auto merge develop branch to XXXXX
on:
  pull_request:
    branches:
      - 'develop'
    types: [ closed ]

jobs:
  merge-branch:
    name: merge-branch
    
    # needed so the Slack message sends after is merge fails
    continue-on-error: true 
    runs-on: ubuntu-latest
    steps:
      #checkout MASTER
      - uses: actions/checkout@master

      - name: debug
        run: echo $GITHUB_BASE_REF to $GITHUB_HEAD_REF
        
      #merge 
      - name: Merge to branch
        uses: devmasx/merge-branch@v1.1.0
        if: github.head_ref == 'master' && pull_request.merged == 'true'
        with:
          type: now
          target_branch: 'sweet'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      #if the merge fails, send a Slack message
      - uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
